### ISSUE TITLE
文件及module创建

### ISSUE THREAD

**Issue by tyh520life** [PrototypeZ/AppJoint#10]
standalone 文件夹是怎么创建的，然后里面的module又是怎么创建的

**Comment by PrototypeZ** [comment]
![image](https://user-images.githubusercontent.com/18358613/48525255-6aeac080-e8be-11e8-9db5-d71280ae5990.png)

创建文件夹只需要按照普通的方式创建即可。

![image](https://user-images.githubusercontent.com/18358613/48525275-83f37180-e8be-11e8-8317-6742ce2297c0.png)

把 module 创建在文件夹里面，需要先创建module，AS 默认会把模块放在项目根目录，我们只要在创建好以后，再把这个模块移动到 standalone 文件夹里即可
