### ISSUE TITLE
没有修改主工程application代码

### ISSUE THREAD

**Issue by trevorwang** [PrototypeZ/AppJoint#11]
压缩文件：com/oriente/cashalo/service/PluginService.class
visiting Lkotlin/Metadata;
visiting Lio/github/prototypez/appjoint/core/ModuleSpec;
visiting Lkotlin/Metadata;
visiting Lio/github/prototypez/appjoint/core/ServiceProvider;
压缩文件：META-INF/MANIFEST.MF
压缩文件：META-INF/analytics_debug.kotlin_module
压缩文件：com/oriente/analytics/AnalyticsApp.class
压缩文件：com/oriente/analytics/BuildConfig.class
压缩文件：com/oriente/analytics/AnalyticsServiceImpl.class
压缩文件：META-INF/MANIFEST.MF
压缩文件：com/oriente/thirdpartylib/BuildConfig.class
moduleApplications: [com/oriente/analytics/AnalyticsApp]
appApplications: [:]
routerAndImpl: [com/oriente/moduleapi/AnalyticsService:com/oriente/analytics/AnalyticsServiceImpl]
appJointClassFile: /Users/trevorwang/Dev/Android/workspace/cashalo/app/build/intermediates/transforms/ajx/debug/io.github.prototypezapp-joint-core1.5_unzip/io/github/prototypez/appjoint/AppJoint.class
appJointOutputFile: /Users/trevorwang/Dev/Android/workspace/cashalo/app/build/intermediates/transforms/ajx/debug/io.github.prototypezapp-joint-core1.5_repackage/io/github/prototypez/appjoint/AppJoint.class
repackageActions: 1

**Comment by PrototypeZ** [comment]
请问是否在主 Application 添加了 @AppSpec 注解，主 Application 是否是 kotlin 代码？AppJoint 版本、gradle plugin 版本、gradle wrapper 版本，分别是多少？可否加我微信 zjnb1114 进一步讨论一下？谢谢反馈！

**Comment by trevorwang** [comment]
1. 添加了注解
2. 不是kotlin
3. AppJoint 1.5
4. Gradle plugin 3.2.1
5. Gradle wrapper 4.6

**Comment by trevorwang** [comment]
第二天 重新编译成功了
