### ISSUE TITLE
Ambiguous method overloading for method java.io.FileInputStream#<init>.

### ISSUE THREAD

**Issue by breeze1988** [PrototypeZ/AppJoint#17]
下载源码 将core引入工程，运行出现报错
Ambiguous method overloading for method java.io.FileInputStream#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
	[class java.io.FileDescriptor]
	[class java.io.File]
	[class java.lang.String]

**Comment by sisel** [comment]
same issue 
appjoint:1.5, gradle:4.10.1

**Comment by PrototypeZ** [comment]
这个问题是由于在应用了 
`apply plugin: 'app-joint'`
插件的 application 模块，无法引用到 
`implementation "io.github.prototypez:app-joint-core:{latest_version}"`
引起的
