### ISSUE TITLE
你好，关于组件之间互调的Router的一些问题

### ISSUE THREAD

**Issue by spysoos** [PrototypeZ/AppJoint#22]
根据你提出的方法，把各个模块的暴露api通通放到单独的router 模块中，然后由各个模块引用这个router模块。这样确实可行，但是也会出现模块A只是需要模块B的接口，但是却要引用其他的api，这是不是有点多余？如果把每个模块要暴露的api放到单独一个module 然后其他模块按需依赖这些api module 这样设计会不会更改好？就像微信做的那样

**Comment by PrototypeZ** [comment]
您好，我觉得您的想法特别好，我在文章中提出的一种拆分方式是一种比较简单的拆分方式，比较适合写例子，也比较符合我目前开发项目的规模。你的这个建议，我考虑过，我觉得这个方案是可行的，如果您认为您的项目比较适合这种方式进行开发，我觉得完全ok，使用 AppJoint 完全不会限制您使用哪一种方法
