### ISSUE TITLE
Application出现重复初始化

### ISSUE THREAD

**Issue by cbfg5210** [PrototypeZ/AppJoint#23]
Application出现重复初始化，版本1.6.1，这个问题貌似是使用了priority注解才出现的

![2019-05-15_155013](https://user-images.githubusercontent.com/12880545/57757978-38186c80-7729-11e9-8d55-899d50835881.png)

**Comment by cbfg5210** [comment]
clean一次再跑就没这个问题了，没clean的话就会有一个Application会重复调用到。

**Comment by cbfg5210** [comment]
有办法避免这个问题吗？因为每次clean都挺耗时间的，如果不clean，由于重复初始化导致了应用崩溃。

**Comment by PrototypeZ** [comment]
您好，方便更详细描述一下问题吗？我感觉可能和Instant Run 有关系，比如说，修改的是主App类？Router 类？或者修改模块App类后，再增量编译，就能导致复现的？

**Comment by cbfg5210** [comment]
> 您好，方便更详细描述一下问题吗？我感觉可能和Instant Run 有关系，比如说，修改的是主App类？Router 类？或者修改模块App类后，再增量编译，就能导致复现的？

我没有开Instant Run，Run了几次就偶尔出现了，clean了之后再Run或者删除了手机上的app再Run就没有重复初始化。是用了priority这个注解才发现这个问题。

**Comment by LeonDevLifeLog** [comment]
可能 https://github.com/PrototypeZ/AppJoint/pull/18/files#diff-bbc0ff2084f02d1be5ffc85bac4bb09aR461
这里坑出现重复添加的情况,待我修复验证一下

**Comment by BigBigDeBoy** [comment]
我也遇到了 重复执行moduleapplication 继承application 重复执行oncreate

**Comment by chinwetang** [comment]
我发现 moduleapplication 存在两个同class的对象，它会导致重复执行application的oncreate
