### ISSUE TITLE
如果模块A启动模块B的Activity，并需要模块B Activity的结果怎么办？还是用startForResult吗？

### ISSUE THREAD

**Issue by spysoos** [PrototypeZ/AppJoint#24]
如果模块A启动模块B的Activity，并需要模块B Activity的结果怎么办？还是用startForResult吗？

我说一个场景：A,B,C模块的某些操作需要用户登录，如果未登录则走登录流程，并返回登录结果，登录流程在D模块里的某Activity，那么A B C 在进行相应操作前都要检查D登录状态，如果未登录，A B C 怎么才能获取到D的登录结果然后进行后面的操作？

**Comment by PrototypeZ** [comment]
你好，你说的场景确实比较常见，我目前也是把登录流程封装在一个独立的用户模块里的，与其他模块是解耦状态，但是“流程”这个行为不属于 AppJoint 解决的问题的范畴，我之前写过解决流程问题的文章，您要是有兴趣可以看一下：
[如何优雅地构建易维护、可复用的 Android 业务流程](https://juejin.im/post/5b0a7088f265da0db721cf73)
[如何优雅地构建易维护、可复用的 Android 业务流程(二)](https://juejin.im/post/5b6ede81f265da0f9c67d1c2)
