### ISSUE TITLE
好像无法配合bugly热更新或tinker一起使用

### ISSUE THREAD

**Issue by Leelion96** [PrototypeZ/AppJoint#26]
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/98.jar

**Comment by PrototypeZ** [comment]
我这边项目使用Bugly热更新的时候没有任何问题，是否有更详细的错误信息呢？您可以加我微信 zjnb1114

**Comment by Leelion96** [comment]
> 我这边项目使用Bugly热更新的时候没有任何问题，是否有更详细的错误信息呢？您可以加我微信 zjnb1114

啊 谢谢作者大大的回复！ 加您微信就先不用了，太打扰了。这个问题，我先在腾讯bugly团队的demo那里提了issues，这里我复制一下地址，我注意到中间有一个报错提到了appJoint，所以昨天来这边临时提了一个问题。如果可以的话，麻烦您到这里看一下，有具体的报错信息：https://github.com/BuglyDevTeam/Bugly-Android-Demo/issues/148#issue-451352983

**Comment by Leelion96** [comment]
已解决 原来是项目依赖的其中有一个库 也依赖了bugly 而upgrade和普通版的bugly是不能共存的  没有提示  一个一个排除出来  很头痛
