### ISSUE TITLE
在ModuleSpec注解的Application中registerActivityLifecycleCallbacks无效

### ISSUE THREAD

**Issue by cbfg5210** [PrototypeZ/AppJoint#28]
在 ModuleSpec 注解的 Application 中 registerActivityLifecycleCallbacks 无效，监听不到 Activity 的生命周期事件。因为无法在 ModuleSpec 注解的 Application 中获取到主 Application 来 registerActivityLifecycleCallbacks ，所以这个问题貌似暂时还无解。 请问有办法解决吗？

![2019-06-28_174316](https://user-images.githubusercontent.com/12880545/60333699-474b3500-99cc-11e9-8f11-fad4031fc9d9.png)

**Comment by PrototypeZ** [comment]
你好，请不要在 Application 中直接调用，使用 getApplicationContext().registerActivityLifecycleCallbacks 进行调用。因为自己定义的 Application 不一定是真正的 Application 类，请使用getApplicationContext()在运行时获得真正的 Application，即使不使用本框架，这也是一种好的实践，谢谢您的意见

**Comment by cbfg5210** [comment]
> 你好，请不要在 Application 中直接调用，使用 getApplicationContext().registerActivityLifecycleCallbacks 进行调用。因为自己定义的 Application 不一定是真正的 Application 类，请使用getApplicationContext()在运行时获得真正的 Application，即使不使用本框架，这也是一种好的实践，谢谢您的意见

嗯嗯，getApplicationContext() 可以强转成 Application，然后用这个 Application 调用 registerActivityLifecycleCallbacks 就行。
