### ISSUE TITLE
修改主模块代码，再次运行，子模块中获取到的主模块服务为空

### ISSUE THREAD

**Issue by jerryhumor** [PrototypeZ/AppJoint#4]
你好，我在使用您的框架的过程中，发现了一下bug，麻烦您看一下，是我使用的方式不对吗。过程如下：
* 有A、B、C三个模块，A为主模块，B为子模块，C为Router模块。A引用B、C模块，B引用C模块。
* C模块里有一个A的服务接口，并且在A模块中实现这个接口，添加注解@ServiceProvider。
* 在A模块的清单文件中声明启动项为B模块的一个Activity，在B模块的这个Activity中直接调用A的服务。
* 第一次编译运行成功运行，结果正确。
* 修改A模块任何代码（比如添加log），不修改B模块的任何代码，编译运行。B模块中获取到的A模块Service为空。

**Comment by PrototypeZ** [comment]
您好，感谢反馈，您可以发我一下联系的qq或者微信吗？我的邮箱 prototypez@126.com

**Comment by PrototypeZ** [comment]
您好，我刚刚自己按您的方式试了一下，没有发现您说的问题，可否加微信或者QQ进一步交流一下？

**Comment by jerryhumor** [comment]
感谢作者大大，1.4版本已经完美解决！
