### ISSUE TITLE
gradle升级到4.6编译错误

### ISSUE THREAD

**Issue by nianzixin** [PrototypeZ/AppJoint#6]
com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set;

**Comment by PrototypeZ** [comment]
你好，项目引用了插件 'com.novoda.bintray-release' 用来把项目发布到 jcenter ，这个插件目前支持 Gradle 4.5+ 有问题。您可以在 settings.gradle 里面先把 ':core' 和 ':plugin' 这两个模块注释掉，即可编译运行，我会在有空的时候寻找一个替代插件来解决这个问题，谢谢 : )

**Comment by PrototypeZ** [comment]
项目demo已升级 gradle 5.1.1 gradle plugin 3.4.2
