### ISSUE TITLE
运行时报错DexArchiveBuilderException

### ISSUE THREAD

**Issue by SheepYang1993** [PrototypeZ/AppJoint#7]
Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process 
做了以下改动解决了问题。。。

在app下build.gradle添加
```
compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
}
```
gradle版本同步为
```
gradle-4.4-all
com.android.tools.build:gradle:3.1.4
```

**Comment by PrototypeZ** [comment]
请问是否有稳定复现的步骤？这个错误我也见过，一般只要 clean build 就可以了，应该和 compileOptions 关系不大

**Comment by PrototypeZ** [comment]
No further information, closing
