### ISSUE TITLE
ButterKnife在library 模块中和在application 模块中使用方法不一致，请问这个如何解决？

### ISSUE THREAD

**Issue by huoweian** [PrototypeZ/AppJoint#8]

**Comment by PrototypeZ** [comment]
您好，这个问题在 Readme 底部的链接里已经说明了：[『回归初心：极简 Android 组件化方案 — AppJoint』](https://juejin.im/post/5bb9c0d55188255c7566e1e2)
使用文中的方案，只需要考虑 ButterKinfe 处于 library 模块一种情况即可，不需要考虑处于 application 模块下的情况
