### ISSUE TITLE
classpath 'com.android.tools.build:gradle:3.2.1' 编译错误

### ISSUE THREAD

**Issue by Redoteam** [PrototypeZ/AppJoint#9]
报错：java.io.FileNotFoundException:/core/build/intermediates/intermediate-jars/debug/core_repackage/io/github/prototypez/appjoint/AppJoint.class (No such file or directory)
后来我看了demo里的，发现是classpath 'com.android.tools.build:gradle:3.1.4
就改为 classpath 'com.android.tools.build:gradle:3.1.4' 这个问题就解决了

**Comment by PrototypeZ** [comment]
你好，这个错误是你运行自己的项目出现的吗？请问你的项目中有没有一个名为“core”模块？请问能否加我一下微信：zjnb1114，非常感谢您的反馈

**Comment by Redoteam** [comment]
是运行自己的项目，里面有个core模块，我改成classpath 'com.android.tools.build:gradle:3.1.4 就没有问题了，如果是com.android.tools.build:gradle:3.2.1，就要注释掉apply plugin: 'app-joint' ，才能编译过

**Comment by PrototypeZ** [comment]
谢谢反馈，我知道问题在哪里了，我稍后发布一个新版解决这个问题，您现在可以临时先把 core 模块重命名一个新的名字，例如: acore 等等，就可以避免这个问题，感谢反馈~

**Comment by Redoteam** [comment]
好的୧(๑•̀⌄•́๑)૭谢谢回复




| |
18672989951
邮箱：18672989951@163.com
|

Signature is customized by Netease Mail Master

在2018年11月09日 17:52，Prototype Z 写道：

谢谢反馈，我知道问题在哪里了，我稍后发布一个新版解决这个问题，您现在可以临时先把 core 模块重命名一个新的名字，例如: acore 等等，就可以避免这个问题，感谢反馈~

**Comment by Redoteam** [comment]
还有个问题，
> java.io.FileNotFoundException:/acoreui/build/intermediates/intermediate-jars/debug/acoreui_repackage (Is a directory)
我项目里新增了acoreui 模块 包名是com.yl.acoreui ，在主模块里加 apply plugin: 'app-joint'  ，就报错

**Comment by PrototypeZ** [comment]
@Redoteam 您方便加一下我上面的微信吗？这样能更好地跟进您的问题

**Comment by Redoteam** [comment]
加了

**Comment by Snooker-shoot** [comment]
Execution failed for task ':app:transformClassesWithAppJointForAlphaDebug'.
> groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.io.FileInputStream#<init>.
  Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
  	[class java.io.FileDescriptor]
  	[class java.io.File]
  	[class java.lang.String]
